# Generated by Django 4.1.1 on 2025-07-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentattend'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattend',
            name='is_attend',
            field=models.BooleanField(default=True),
        ),
    ]
