# Generated by Django 4.1.1 on 2025-09-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_page_memorizedpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorizedpages',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
