# Generated by Django 5.2.13 on 2026-06-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_student_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('narrator', models.CharField(max_length=200)),
                ('alhadith', models.TextField()),
                ('producer', models.CharField(max_length=200)),
            ],
        ),
    ]
