# Generated by Django 5.2.1 on 2026-06-19 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('image', models.TextField(blank=True, default='')),
                ('activity_type', models.CharField(choices=[('trip', 'رحلة'), ('swimming', 'مسبح'), ('football', 'كرة قدم'), ('horse_riding', 'ركوب خيل'), ('other', 'نشاط آخر')], max_length=30)),
                ('other_activity_type', models.CharField(blank=True, default='', max_length=200)),
                ('attended_students', models.ManyToManyField(blank=True, related_name='activities', to='core.student')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities_created', to='core.user')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('attended_students', models.ManyToManyField(blank=True, related_name='lessons', to='core.student')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_created', to='core.user')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
