# Generated by Django 5.2.1 on 2026-06-21 18:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


POINT_RULES = [
    {
        'code': 'attendance_on_time',
        'name': 'الحضور عند بداية الدوام',
        'category': 'الحضور',
        'direction': 'addition',
        'calculation_method': 'fixed',
        'default_points': '5.00',
        'sort_order': 10,
    },
    {
        'code': 'memorization_pages',
        'name': 'الحفظ',
        'category': 'الحفظ',
        'direction': 'addition',
        'calculation_method': 'memorization',
        'default_points': '0.00',
        'config': {
            'thresholds': {
                '1': '5',
                '2': '15',
                '3': '25',
                '4': '40',
            },
            'extra_page_rate': '5',
        },
        'sort_order': 20,
    },
    {
        'code': 'dress_code',
        'name': 'ارتداء الكلابية والطاقية',
        'category': 'اللباس',
        'direction': 'addition',
        'calculation_method': 'fixed',
        'default_points': '5.00',
        'sort_order': 30,
    },
    {
        'code': 'hadith_recitation',
        'name': 'تسميع الحديث',
        'category': 'الحديث',
        'direction': 'addition',
        'calculation_method': 'fixed',
        'default_points': '5.00',
        'sort_order': 40,
    },
    {
        'code': 'participation_regular',
        'name': 'مشاركة عادية',
        'category': 'المشاركة',
        'direction': 'addition',
        'calculation_method': 'fixed',
        'default_points': '5.00',
        'sort_order': 50,
    },
    {
        'code': 'participation_special',
        'name': 'مشاركة مميزة',
        'category': 'المشاركة',
        'direction': 'addition',
        'calculation_method': 'fixed',
        'default_points': '15.00',
        'sort_order': 60,
    },
    {
        'code': 'good_behavior_weekly',
        'name': 'السلوك الحسن خلال الأسبوع',
        'category': 'السلوك الحسن',
        'direction': 'addition',
        'calculation_method': 'fixed',
        'default_points': '15.00',
        'sort_order': 70,
    },
    {
        'code': 'exam_first_attempt',
        'name': 'النجاح من أول مرة',
        'category': 'الاختبارات',
        'direction': 'addition',
        'calculation_method': 'fixed',
        'default_points': '50.00',
        'sort_order': 80,
    },
    {
        'code': 'exam_second_attempt',
        'name': 'النجاح من ثاني مرة',
        'category': 'الاختبارات',
        'direction': 'addition',
        'calculation_method': 'fixed',
        'default_points': '40.00',
        'sort_order': 90,
    },
    {
        'code': 'exam_third_attempt',
        'name': 'النجاح من ثالث مرة',
        'category': 'الاختبارات',
        'direction': 'addition',
        'calculation_method': 'fixed',
        'default_points': '25.00',
        'sort_order': 100,
    },
    {
        'code': 'awqaf_completion',
        'name': 'إتمام سير الأوقاف',
        'category': 'سير الأوقاف',
        'direction': 'addition',
        'calculation_method': 'fixed',
        'default_points': '100.00',
        'sort_order': 110,
    },
    {
        'code': 'absence',
        'name': 'الغياب',
        'category': 'الخصومات',
        'direction': 'deduction',
        'calculation_method': 'fixed',
        'default_points': '10.00',
        'sort_order': 120,
    },
    {
        'code': 'present_without_recitation',
        'name': 'حضر ولم يسمع',
        'category': 'الخصومات',
        'direction': 'deduction',
        'calculation_method': 'fixed',
        'default_points': '5.00',
        'sort_order': 130,
    },
    {
        'code': 'early_leave',
        'name': 'الخروج قبل انتهاء الوقت',
        'category': 'الخصومات',
        'direction': 'deduction',
        'calculation_method': 'fixed',
        'default_points': '5.00',
        'sort_order': 140,
    },
    {
        'code': 'awqaf_absence_or_failure',
        'name': 'الغياب أو الرسوب في سير الأوقاف',
        'category': 'الخصومات',
        'direction': 'deduction',
        'calculation_method': 'fixed',
        'default_points': '25.00',
        'sort_order': 150,
    },
    {
        'code': 'negative_behavior',
        'name': 'السلوك السلبي',
        'category': 'الخصومات',
        'direction': 'deduction',
        'calculation_method': 'fixed',
        'default_points': '10.00',
        'sort_order': 160,
    },
]


SURAHS_DATA = {
    'الملك': {'surah_number': 67, 'juz': 'تبارك', 'pages': '2.50'},
    'القلم': {'surah_number': 68, 'juz': 'تبارك', 'pages': '2.50'},
    'الحاقة': {'surah_number': 69, 'juz': 'تبارك', 'pages': '2.00'},
    'المعارج': {'surah_number': 70, 'juz': 'تبارك', 'pages': '1.50'},
    'نوح': {'surah_number': 71, 'juz': 'تبارك', 'pages': '1.50'},
    'الجن': {'surah_number': 72, 'juz': 'تبارك', 'pages': '2.00'},
    'المزمل': {'surah_number': 73, 'juz': 'تبارك', 'pages': '1.00'},
    'المدثر': {'surah_number': 74, 'juz': 'تبارك', 'pages': '2.00'},
    'القيامة': {'surah_number': 75, 'juz': 'تبارك', 'pages': '1.00'},
    'الإنسان': {'surah_number': 76, 'juz': 'تبارك', 'pages': '2.00'},
    'المرسلات': {'surah_number': 77, 'juz': 'تبارك', 'pages': '1.50'},
    'النبأ': {'surah_number': 78, 'juz': 'عم', 'pages': '1.50'},
    'النازعات': {'surah_number': 79, 'juz': 'عم', 'pages': '1.50'},
    'عبس': {'surah_number': 80, 'juz': 'عم', 'pages': '1.50'},
    'التكوير': {'surah_number': 81, 'juz': 'عم', 'pages': '1.00'},
    'الانفطار': {'surah_number': 82, 'juz': 'عم', 'pages': '1.00'},
    'المطففين': {'surah_number': 83, 'juz': 'عم', 'pages': '2.00'},
    'الانشقاق': {'surah_number': 84, 'juz': 'عم', 'pages': '1.00'},
    'البروج': {'surah_number': 85, 'juz': 'عم', 'pages': '1.00'},
    'الطارق': {'surah_number': 86, 'juz': 'عم', 'pages': '1.00'},
    'الأعلى': {'surah_number': 87, 'juz': 'عم', 'pages': '1.00'},
    'الغاشية': {'surah_number': 88, 'juz': 'عم', 'pages': '1.00'},
    'الفجر': {'surah_number': 89, 'juz': 'عم', 'pages': '1.50'},
    'البلد': {'surah_number': 90, 'juz': 'عم', 'pages': '1.00'},
    'الشمس': {'surah_number': 91, 'juz': 'عم', 'pages': '1.00'},
    'الليل': {'surah_number': 92, 'juz': 'عم', 'pages': '1.00'},
    'الضحى': {'surah_number': 93, 'juz': 'عم', 'pages': '0.50'},
    'الشرح': {'surah_number': 94, 'juz': 'عم', 'pages': '0.50'},
    'التين': {'surah_number': 95, 'juz': 'عم', 'pages': '0.50'},
    'العلق': {'surah_number': 96, 'juz': 'عم', 'pages': '1.00'},
    'القدر': {'surah_number': 97, 'juz': 'عم', 'pages': '0.50'},
    'البينة': {'surah_number': 98, 'juz': 'عم', 'pages': '1.00'},
    'الزلزلة': {'surah_number': 99, 'juz': 'عم', 'pages': '0.50'},
    'العاديات': {'surah_number': 100, 'juz': 'عم', 'pages': '0.50'},
    'القارعة': {'surah_number': 101, 'juz': 'عم', 'pages': '0.50'},
    'التكاثر': {'surah_number': 102, 'juz': 'عم', 'pages': '0.50'},
    'العصر': {'surah_number': 103, 'juz': 'عم', 'pages': '0.25'},
    'الهمزة': {'surah_number': 104, 'juz': 'عم', 'pages': '0.50'},
    'الفيل': {'surah_number': 105, 'juz': 'عم', 'pages': '0.25'},
    'قريش': {'surah_number': 106, 'juz': 'عم', 'pages': '0.25'},
    'الماعون': {'surah_number': 107, 'juz': 'عم', 'pages': '0.50'},
    'الكوثر': {'surah_number': 108, 'juz': 'عم', 'pages': '0.25'},
    'الكافرون': {'surah_number': 109, 'juz': 'عم', 'pages': '0.25'},
    'النصر': {'surah_number': 110, 'juz': 'عم', 'pages': '0.25'},
    'المسد': {'surah_number': 111, 'juz': 'عم', 'pages': '0.25'},
    'الإخلاص': {'surah_number': 112, 'juz': 'عم', 'pages': '0.25'},
    'الفلق': {'surah_number': 113, 'juz': 'عم', 'pages': '0.25'},
    'الناس': {'surah_number': 114, 'juz': 'عم', 'pages': '0.25'},
}


def seed_points_defaults(apps, schema_editor):
    PointRule = apps.get_model('core', 'PointRule')
    SurahPageData = apps.get_model('core', 'SurahPageData')

    for rule in POINT_RULES:
        PointRule.objects.update_or_create(
            code=rule['code'],
            defaults=rule,
        )

    for name, data in SURAHS_DATA.items():
        SurahPageData.objects.update_or_create(
            surah_number=data['surah_number'],
            juz=data['juz'],
            defaults={
                'name': name,
                'pages': data['pages'],
                'is_active': True,
                'metadata': {},
            },
        )


def remove_points_defaults(apps, schema_editor):
    PointRule = apps.get_model('core', 'PointRule')
    SurahPageData = apps.get_model('core', 'SurahPageData')
    PointRule.objects.filter(code__in=[rule['code'] for rule in POINT_RULES]).delete()
    SurahPageData.objects.filter(surah_number__gte=67, surah_number__lte=114).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_activity_image_activityteacherassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('addition', 'إضافة'), ('deduction', 'خصم')], default='addition', max_length=20)),
                ('calculation_method', models.CharField(choices=[('fixed', 'قيمة ثابتة'), ('memorization', 'احتساب الحفظ')], default='fixed', max_length=30)),
                ('default_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SurahPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surah_number', models.PositiveIntegerField()),
                ('juz', models.CharField(max_length=100)),
                ('pages', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['surah_number'],
                'unique_together': {('surah_number', 'juz')},
            },
        ),
        migrations.CreateModel(
            name='StudentPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_method', models.CharField(choices=[('manual', 'يدوي'), ('direct_pages', 'عدد الصفحات'), ('surah', 'السورة'), ('system', 'آلي')], default='manual', max_length=30)),
                ('operation_date', models.DateField(default=datetime.date.today)),
                ('memorized_pages', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.pointrule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='core.student')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='core.user')),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.surahpagedata')),
            ],
            options={
                'ordering': ['-operation_date', '-id'],
            },
        ),
        migrations.RunPython(seed_points_defaults, remove_points_defaults),
    ]
