# Generated by Django 5.2.1 on 2026-06-21 21:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pointrule_student_total_points_surahpagedata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('points', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_behaviors', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_behaviors', to='core.user')),
            ],
            options={
                'ordering': ['-week_start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('good', 'جيدة'), ('bad', 'سيئة')], default='good', max_length=10)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note_text', models.TextField()),
                ('note_date', models.DateField(default=datetime.date.today)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.user')),
            ],
            options={
                'ordering': ['-note_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StudentBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorization_type', models.CharField(blank=True, choices=[('page', 'صفحة'), ('surah', 'سورة')], max_length=20, null=True)),
                ('memorization_value', models.CharField(blank=True, default='', max_length=200)),
                ('memorization_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_attended', models.BooleanField(default=False)),
                ('attendance_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_clothing', models.BooleanField(default=False)),
                ('clothing_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('has_cap', models.BooleanField(default=False)),
                ('cap_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('participation_type', models.CharField(blank=True, choices=[('special', 'مميز'), ('normal', 'عادي')], max_length=20, null=True)),
                ('participation_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('was_absent', models.BooleanField(default=False)),
                ('absence_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('no_recitation', models.BooleanField(default=False)),
                ('no_recitation_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('left_early', models.BooleanField(default=False)),
                ('left_early_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('behavior_date', models.DateField(default=datetime.date.today)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_behaviors', to='core.user')),
            ],
            options={
                'ordering': ['-behavior_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[('stop', 'وقف'), ('internal', 'داخلي')], default='internal', max_length=20)),
                ('attempt_number', models.IntegerField(default=1)),
                ('evaluation', models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جداً'), ('good', 'جيد'), ('average', 'وسط'), ('failed', 'رسوب')], max_length=20, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('test_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, default='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.user')),
            ],
            options={
                'ordering': ['-test_date', '-id'],
            },
        ),
    ]
