# Generated by Django 5.2.1 on 2026-06-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_goodbehavior_note_studentbehavior_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('external', 'وقف'), ('internal', 'داخلي')], default='internal', max_length=20),
        ),
    ]
