# Generated by Django 5.2.1 on 2026-06-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_studentbehavior_absence_penalty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbehavior',
            name='memorization_pages',
        ),
        migrations.RemoveField(
            model_name='studentbehavior',
            name='memorization_type',
        ),
        migrations.RemoveField(
            model_name='studentbehavior',
            name='memorization_value',
        ),
    ]
