# Generated by Django 4.1.1 on 2025-07-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
