# Generated by Django 4.1.1 on 2025-07-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_groupsession_id_alter_groupsession_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsession',
            name='id',
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.student'),
        ),
    ]
