# Generated by Django 5.2.1 on 2026-06-19 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_activity_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='activities/'),
        ),
        migrations.CreateModel(
            name='ActivityTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.activity')),
                ('students', models.ManyToManyField(blank=True, related_name='activity_teacher_assignments', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_assignments', to='core.user')),
            ],
            options={
                'ordering': ['teacher__username', 'id'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'teacher'), name='unique_activity_teacher_assignment')],
            },
        ),
        migrations.CreateModel(
            name='LessonTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.lesson')),
                ('students', models.ManyToManyField(blank=True, related_name='lesson_teacher_assignments', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assignments', to='core.user')),
            ],
            options={
                'ordering': ['teacher__username', 'id'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'teacher'), name='unique_lesson_teacher_assignment')],
            },
        ),
    ]
