# Generated by Django 5.2.1 on 2026-06-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_test_test_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbehavior',
            name='absence_penalty',
        ),
        migrations.RemoveField(
            model_name='studentbehavior',
            name='attendance_points',
        ),
        migrations.RemoveField(
            model_name='studentbehavior',
            name='cap_points',
        ),
        migrations.RemoveField(
            model_name='studentbehavior',
            name='clothing_points',
        ),
        migrations.RemoveField(
            model_name='studentbehavior',
            name='left_early_penalty',
        ),
        migrations.RemoveField(
            model_name='studentbehavior',
            name='memorization_points',
        ),
        migrations.RemoveField(
            model_name='studentbehavior',
            name='no_recitation_penalty',
        ),
        migrations.RemoveField(
            model_name='studentbehavior',
            name='participation_points',
        ),
        migrations.AddField(
            model_name='studentbehavior',
            name='memorization_pages',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
