# Generated by Django 5.2.14 on 2026-06-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_update_memorization_extra_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Juz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("juz_number", models.PositiveIntegerField(unique=True)),
                ("start_page", models.PositiveIntegerField()),
                ("end_page", models.PositiveIntegerField()),
                ("total_pages", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["juz_number"],
            },
        ),
        migrations.AddField(
            model_name="surahpagedata",
            name="end_page",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surahpagedata",
            name="end_page_decimal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="surahpagedata",
            name="juz_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surahpagedata",
            name="start_page",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surahpagedata",
            name="start_page_decimal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="surahpagedata",
            name="surah_name_arabic",
            field=models.CharField(default="", max_length=100),
        ),
    ]
