# Generated by Django 5.2.14 on 2026-06-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_juz_surahpagedata_end_page_and_more"),
        ("core", "0029_system_settings"),
    ]

    operations = []
